config/routes.rb
Rails.application.routes.draw do
  root to: "users#friends"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :rooms do
    get :members, on: :member
  end
  resources :users, param: :user_id, path: "/", only: %i(show) do
    get :search, on: :collection
    get :friends, on: :member
  end
  resources :friend_requests, only: %i(create destroy update)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy

  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users

  has_many :friend_requests, foreign_key: :requester_id, dependent: :destroy
  has_many :friends, -> { where(friend_requests: { approved: true }) }, through: :friend_requests, source: :reciever

  validates :name, presence: true, length: { maximum: 20 }
  validates :user_id, presence: true, uniqueness: true, length: { maximum: 15 }
  validate  :icon_size

  mount_uploader :icon, UserIconUploader

  def join_to_room(room)
    self.rooms << room
  end

  def joined?(room)
    self.rooms.include?(room)
  end

  def send_friend_request(user)
    self.friend_requests.create(reciever: user)
  end

  def approve_friend_request(friend_request)
    friend_request.update_attribute(:approved, true)
    self.friend_requests.create(reciever: friend_request.requester, approved: true)
  end

  def delete_from_friends(user)
    FriendRequest.where(requester_id: self.id, reciever_id: user.id).
      or(FriendRequest.where(requester_id: user.id, reciever_id: self.id)).
        each { |f| f.destroy }
  end

  def friend?(user)
    self.friends.include?(user)
  end

  def waiting_for_approval?(user)
    self.friend_requests.exists?(reciever_id: user.id, approved: false)
  end

  def recieved_request_from?(user)
    user.friend_requests.exists?(reciever_id: self.id, approved: false)
  end

  private

    def icon_size
      if icon.size > 5.megabytes
        errors.add(:icon, "should be less than 5MB")
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  include UsersHelper
  before_action :authenticate_user!

  def show
    @user = User.find_by(user_id: params[:user_id])
  end

  def friends
    set_friends_and_requests
  end

  def search
    if params[:search].blank?
      flash[:danger] = "Please enter the user_id."
      redirect_to root_url
    elsif User.exists?(user_id: params[:search])
      redirect_to user_path(params[:search])
    else
      flash.now[:danger] = "Cannot find a user."
      @search_value = params[:search]
      set_friends_and_requests
      render "friends"
    end
  end

  private

    def set_friends_and_requests
      user = User.find_by(user_id: current_user.user_id)
      @users = user.friends.order(name: :asc)
      @friend_requests = FriendRequest.new_request_to(current_user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    current_user == user
  end
end

app/views/users/_approve_request.html.erb
<%= form_with(model: friend_request, id: "approve_btn") do |f| %>
  <%= f.submit "Approve Request", class: "btn btn-success" %>
<% end %>

app/views/users/_friend_or_delete.html.erb
<h4>Friend</h4>
<%= form_with(model: current_user.friend_requests.find_by(reciever_id: @user.id), method: :delete) do |f| %>
  <%= hidden_field_tag(:user_id, @user.id) %>
  <%= f.submit "Delete from the Friend", class: "btn btn-danger", id: "delete-btn" %>
<% end %>

app/views/users/_friend_request_form.html.erb
<div id="friend_request_form">
  <% if current_user.friend?(@user) %>
    <%= render "friend_or_delete" %>
  <% elsif current_user.waiting_for_approval?(@user) %>
    <%= render "wait_or_cancel" %>
  <% elsif current_user.recieved_request_from?(@user) %>
    <%= render "approve_request", friend_request: @user.friend_requests.find_by(reciever_id: current_user.id, approved: false) %>
  <% else %>
    <%= render "request" %>
  <% end %>
</div>

app/views/users/_request.html.erb
<%= form_with(model: current_user.friend_requests.build) do |f| %>
  <%= hidden_field_tag(:reciever_id, @user.id) %>
  <%= f.submit "Send Friend Request", class: "btn btn-success", id: "request-btn" %>
<% end %>

app/views/users/_user.html.erb
<div>
  <%= link_to user_path(user.user_id), class: "hover-gray" do %>
    <div class="user flex">
      <div class="user-icon">
        <%= image_tag user.icon.small.url, class: "radius", width: "40px" %>
      </div>
      <div class="name">
        <h4><%= user.name %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_wait_or_cancel.html.erb
<h4>Already sent friend request.</h4>
<%= form_with(model: current_user.friend_requests.find_by(reciever_id: @user.id), method: :delete) do |f| %>
  <%= hidden_field_tag(:friend_id, @user.id) %>
  <%= f.submit "Cancel the Request", class: "btn btn-danger", id: "cancel-btn" %>
<% end %>

app/views/users/friends.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Friends</h1>
    <div>
      <%= form_with(model: @search, url: search_users_path, method: :get, local: true) do |f| %>
        <%= f.text_field :search, value: @search_value %>
        <%= f.submit "Search by User ID", class: "btn btn-success" %>
      <% end %>
    </div>
    <h4>Your Profile</h4>
    <div class="user flex">
      <div class="user-icon">
        <%= image_tag current_user.icon.small.url, class: "radius", width: "40px" %>
      </div>
      <h4 class="name"><%= link_to current_user.name, user_path(current_user.user_id) %></h4>
    </div>
    <div id="requests">
      <h4>New Friend Requests (<%= @friend_requests.count %>)</h4>
      <%= render @friend_requests if @friend_requests.present? %>
    </div>
    <div id="users">
      <h4>Your Friends (<%= @users.count %>)</h4>
      <%= render @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div id="profile">
      <div class="user-icon">
        <%= image_tag @user.icon.middle.url, class: "radius", width: "120px" %>
      </div>
      <h1><%= @user.name %></h1>
      <% unless current_user?(@user) %>
        <%= render "friend_request_form" %>
      <% end %>
      <% if current_user?(@user) %>
        <%= link_to "settings", edit_user_registration_path, class: "settings" %>
      <% end %>
    </div>
  </div>
</div>