config/routes.rb
Rails.application.routes.draw do
  root to: "users#friends"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :rooms do
    get :members, on: :member
  end
  resources :users, param: :user_id, path: "/", only: %i(show) do
    get :search, on: :collection
    get :friends, on: :member
  end
  resources :friend_requests, only: %i(create destroy update)
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users

  validates :name, presence: true, length: { maximum: 20 }
  validate  :icon_size

  mount_uploader :icon, RoomIconUploader

  private
  
    def icon_size
      if icon.size > 5.megabytes
        errors.add(:icon, "should be less than 5MB")
      end
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :joined_user?, only: %i(edit update)

  def index
    @rooms = Room.all
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    if @room.save
      flash[:success] = "room created!"
      current_user.join_to_room(@room)
      redirect_to rooms_path
    else
      @rooms = Room.all
      render "rooms/index"
    end
  end

  def show
    @room = Room.find(params[:id])
    unless current_user.joined?(@room)
      current_user.join_to_room(@room)
    end
    @messages = @room.messages.includes(:user)
  end

  def members
    @room = Room.find(params[:id])
    @users = @room.users
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    if @room.update_attributes(room_params)
      flash[:success] = "Successfully updated room"
      redirect_to room_path(@room)
    else
      render "edit"
    end
  end

  private

    def room_params
      params.require(:room).permit(:name, :icon)
    end

    def joined_user?
      @room = Room.find(params[:id])
      redirect_to root_url unless current_user.joined?(@room)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def latest_message(room)
    msg = room.messages.last
    content_tag(:h4, msg.content, class: "content") if msg.present?
  end

  def posted_time_of_latest_message(room)
    msg = room.messages.last
    content_tag(:span, l(msg.created_at)) if msg.present?
  end
end

app/views/rooms/_room.html.erb
<div class="room">
  <%= link_to room_path(room), class: "hover-gray" do %>
    <div class="main flex">
      <div class="room-icon flex">
        <%= image_tag room.icon.small.url, class: "radius", width: "60px", height: "60px" %>
      </div>
      <div class="name-and-content flex-column">
        <h4 class="name"><%= "#{room.name} (#{room.messages.count})" %></h4>
        <%= latest_message(room) %>
      </div>
      <%= posted_time_of_latest_message(room) %>
    </div>
  <% end %>
  <div>
    <%= link_to "settings", edit_room_path(room) %>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= provide(:title, "Room Settings") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="center">
      <%= image_tag @room.icon.middle.url, class: "radius", width: "120px" %>
    </div>
    <%= form_with(model: @room, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <span class="room-icon">
        <span>Room Icon</span>
        <%= f.file_field :icon, accept: 'image/jpeg, image/gif, image/png' %>
      </span>
      <%= f.submit "Save", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<%= provide(:title, "Chat Rooms") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Chat Rooms</h1>
    <div id="rooms">
      <%= render @rooms %>
    </div>

    <% if user_signed_in? %>
      <%= form_for(@room) do |f|%> 
        <%= f.label :name, "room name :" %>
        <%= f.text_field :name %>
        <%= f.submit "create new room", class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/members.html.erb
<%= provide(:title, "Members of #{@room.name}") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Members of <%= @room.name %></h1>
    <div id="users">
      <%= render @users %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<%= provide(:title, @room.name) %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="room-prof flex">
      <h1><%= @room.name %></h1>
      <%= link_to "settings", edit_room_path(@room) %>
      <%= link_to "chat members", members_room_path(@room) %>
    </div>
    <div id="messages" data-room_id="<%= @room.id %>">
      <%= render @messages %>
    </div>
  </div>
</div>

<div class="navbar navbar-fixed-bottom navbar-default">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      <textarea type="text" data-behavior="room_speaker"></textarea>
      </div>
    </div>
  </div>
</div>