config/routes.rb
Rails.application.routes.draw do
  root to: "users#friends"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :rooms do
    get :members, on: :member
  end
  resources :users, param: :user_id, path: "/", only: %i(show) do
    get :search, on: :collection
    get :friends, on: :member
  end
  resources :friend_requests, only: %i(create destroy update)
end

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% if user_signed_in? %>
          <%= link_to "Friends", root_path, class: "navbar-brand" %>
          <%= link_to "Rooms",  rooms_path, class: "navbar-brand" %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, user_path(current_user.user_id) %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>   
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <% flash.each do |flash_type, message| %>
            <div class="alert alert-<%= "#{flash_type}" %>"><%= message %></div>
          <% end %>
        </div>
      </div>
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>